name: project                                                              
channels:                                                                    
  - defaults                                                                 
dependencies:                                                                
  - numpy
  - matplotlib=3.7.1
  - make
  - seaborn
  - pandas=2.0.3
  - curl
  - scikit-learn
  - xgboost