CARDIAC_ARREST_DATE_TIME = "eArrest_14"

# FACTPCRARRESTWITNESS_CA.csv
CARDIAC_ARREST_WITNESS = 'eArrest_04'
# CA_eID.csv
CARDIAC_ARREST_CPR = "eArrest_01"

# Pub_PCRevents_CA.csv
CARDIAC_ARREST_ETIOLOGY = 'eArrest_02'
# Pub_PCRevents_CA.csv
CARDIAC_ARREST_CPR_PRIOR_TO_EMS = 'eArrest_05'

CARDIAC_ARREST_CPR_DISCONTINUED = "eArrest_16"
# Pub_PCRevents_CA.csv
CARDIAC_ARREST_AED_PRIOR_EMS = 'eArrest_07'
# Pub_PCRevents_CA.csv
# shockable vs non-shockable?
CARDIAC_ARREST_FIRST_MONITORED_RYTHM = 'eArrest_11'
# Pub_PCRevents_CA.csv
CARDIAC_ARREST_OUTCOME = "eArrest_18"
# PART OF OUTCOME
CARDIAC_ARREST_SPONTANEOUS_CIRCULATION = "eArrest_12"

# Pub_PCRevents_CA.csv
PATIENT_AGE = 'ePatient_15'

# ComputedElements_CA.csv
GENDER = 'ePatient_13'

# PCRPATIENTRACEGROUP_CA.csv
RACE = 'ePatient_14'

# ComputedElements_CA.csv
URBANICITY = 'urbanicity'

# ComputedElements_CA.csv
AGE_IN_YEAR = 'ageinyear' 

# FACTPCRMEDICATION_CA.csv
MEDICATIONS = 'eMedications_03'

DOSE = 'eMedications_05'
MEDICAL_HISTORY = 'eHistory_17'

# Call to patient time
# Pub_PCRevents_CA.csv
CALL_TIME = 'eTimes_01'
PATIENT_TIME = 'eTimes_07'


# RESPONSE ELEMENTS
# Pub_PCRevents_CA.csv
PRIMARY_ROLE = 'eResponse_07'

# LIKELY NOT NECESSARY WITH CALL TO PATIENT_TIME
# FACTPCRDISPATCHDELAY_CA.csv
DISPATCH_DELAY = 'eResponse_08'

# LIKELY NOT NECESSARY WITH CALL TO PATIENT_TIME
# FACTPCRRESPONSEDELAY_CA.csv
RESPONSE_DELAY = 'eResponse_09'

# FACTPCRSCENEDELAY_CA.csv
SCENE_DELAY = 'eResponse_10'

# FACTPCRTRANSPORTDELAY_CA.csv
TURN_AROUND_DELAY = 'eResponse_11'

# Pub_PCRevents_CA.csv
LEVEL_OF_CARE = 'eResponse_15'

# PAYMENT METHOD
# Pub_PCRevents_CA.csv
PAYMENT_METHOD = 'ePayment_01'

# SCENE TIME
SCENE_ARRIVAL = 'eTimes_06'
SCENE_DEPARTURE = 'eTimes_09'

# TRANSPORT TIME
DESTINATION_ARRIVAL = 'eTimes_11'

PATIENT_DISPOSITION = 'eDisposition_12'
TYPE_OF_DESTINATION = 'eDisposition_21'

CARDIAC_RHYTHM = 'eVitals_04'
HEART_RATE = 'eVitals_10'


